### ISSUE TITLE
linter fails because prettier uses 2 spaces, fmt uses 4 spaces

### ISSUE THREAD

**Issue by vmaark** [PaulRBerg/foundry-template#10]
tab size is configured differently for `sol` in the 2 tools, causing the linter to fail, if prettier was used for formatting. editorconfig also sets indent size to 2.

**Comment by PaulRBerg** [comment]
This is not an issue with the template itself. You can refer to the [Formatter](https://book.getfoundry.sh/config/vscode#3-formatter) section of the "Integrating with Foundry" guide of the Foundry Book for how to configure VSCode to not run Prettier on Solidity files. In short, you have to add this to your VSCode settings:

```json
"[solidity]": {
    "editor.defaultFormatter": "JuanBlanco.vscode-solidity" 
  },
```

**Comment by vmaark** [comment]
That may be true, but it would still be better not to use different values for tabwidth.

**Comment by PaulRBerg** [comment]
This is a good point! Let me think about this - really the only reason for keeping 2 spaces for tab width is formatting for JSON files. I might just add an override for `*.json` and set the default to 4.

**Comment by PaulRBerg** [comment]
[I ended up doing something else](https://github.com/PaulRBerg/foundry-template/commit/adcec923c68ae25c01b81214ef2a35d78f00783c) - I have kept the default `tabWidth` to 2 but I have also added an override for Solidity to use 4, like this:

```json
overrides:
  - files: ["*.sol"]
    options:
      tabWidth: 4
```

Otherwise, I would have had to add quite a few overrides:

```json
- files: ["*.json", "*.md", "*.yml"]
```

Even if Prettier is not run over Solidity files, this should make the template more robust for end users, since it will prevent accidental re-formatting when the VSCode settings are not configured on a per-language basis.

Thanks for opening this issue, @vmaark.
